"""Confluence integration (FR-12) — publish a research report as a page."""
from __future__ import annotations

from config import get_settings


class ConfluenceIntegration:
    def __init__(self) -> None:
        self.settings = get_settings()
        self._client = None

    @property
    def client(self):
        if self._client is None:
            if not (self.settings.confluence_url and self.settings.confluence_token):
                raise ValueError("CONFLUENCE_URL / CONFLUENCE_TOKEN not configured")
            from atlassian import Confluence

            self._client = Confluence(
                url=self.settings.confluence_url,
                username=self.settings.jira_email or None,
                password=self.settings.confluence_token,
                cloud=True,
            )
        return self._client

    def publish_report(self, space_key: str, insights: list[dict], title: str = "ORION Research Report") -> dict:
        body = self._body(insights)
        page = self.client.create_page(space=space_key, title=title, body=body, representation="storage")
        return {"page_id": page.get("id"), "title": title, "space": space_key}

    @staticmethod
    def _body(insights: list[dict]) -> str:
        rows = "".join(
            f"<li><b>{i.get('title','')}</b> ({i.get('type','')}, conf {i.get('confidence','')}): "
            f"{i.get('summary','')}</li>"
            for i in insights
        )
        return f"<h2>Insights</h2><ul>{rows}</ul><hr/><p><i>Generated by ORION.</i></p>"
