"""GitHub integration (FR-12) — write-only: create labelled issues from insights."""
from __future__ import annotations

from config import get_settings


class GitHubIntegration:
    def __init__(self) -> None:
        self.settings = get_settings()
        self._client = None

    @property
    def client(self):
        if self._client is None:
            if not self.settings.github_token:
                raise ValueError("GITHUB_TOKEN not configured")
            from github import Github

            self._client = Github(self.settings.github_token)
        return self._client

    def create_issue_from_insight(self, repo_name: str, insight: dict) -> dict:
        repo = self.client.get_repo(repo_name)
        labels = ["research-finding"]
        if insight.get("confidence", 0) > 0.8:
            labels.append("high-confidence")
        if insight.get("type") == "hypothesis":
            labels.append("hypothesis")
        issue = repo.create_issue(
            title=f"[Research] {insight['title']}",
            body=self._body(insight),
            labels=[l for l in labels if self._label_exists(repo, l)],
        )
        return {"issue_number": issue.number, "url": issue.html_url}

    @staticmethod
    def _body(insight: dict) -> str:
        sources = "\n".join(f"- [{s.get('title','src')}]({s.get('url','')})" for s in insight.get("sources", []))
        evidence = "\n".join(f"- {e}" for e in insight.get("evidence", []))
        return (
            f"## Research Finding\n\n"
            f"**Confidence:** {insight.get('confidence','N/A')}\n\n"
            f"### Summary\n{insight.get('summary','')}\n\n"
            f"### Evidence\n{evidence}\n\n### Sources\n{sources}\n\n"
            f"---\n*Generated by ORION Multi-Agent Researcher*\n"
        )

    @staticmethod
    def _label_exists(repo, name: str) -> bool:
        try:
            repo.get_label(name)
            return True
        except Exception:
            return False
